[package]
name = "sqlc-gen-rust"
version = "0.1.0"
edition = "2024"
authors = ["tunamaguro"]
license = "MIT OR Apache-2.0"

[dependencies]
prost = { version = "0.14" }

[build-dependencies]
prost-build = "0.14"