services:
  dev:
    build:
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
  postgres:
    image: postgres:17.0-bookworm
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
  mysql:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      