//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.28.0
//! sqlc-gen-rust version: v0.1.11

#[derive(sqlx::FromRow)]
pub struct ListAuthorsByIDsRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
}
pub struct ListAuthorsByIDs<'a> {
    ids: &'a [i64],
}
impl<'a> ListAuthorsByIDs<'a> {
    pub const QUERY: &'static str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?)
ORDER BY id";
    pub fn query_as(
        &'a self,
    ) -> sqlx::query::QueryAs<
        'a,
        sqlx::Sqlite,
        ListAuthorsByIDsRow,
        <sqlx::Sqlite as sqlx::Database>::Arguments<'a>,
    > {
        sqlx::query_as::<_, ListAuthorsByIDsRow>(Self::QUERY).bind(self.ids)
    }
    pub fn query_many<'b, A>(
        &'a self,
        conn: A,
    ) -> impl Future<Output = Result<Vec<ListAuthorsByIDsRow>, sqlx::Error>> + Send + 'a
    where
        A: sqlx::Acquire<'b, Database = sqlx::Sqlite> + Send + 'a,
    {
        async move {
            let mut conn = conn.acquire().await?;
            let vals = self.query_as().fetch_all(&mut *conn).await?;
            Ok(vals)
        }
    }
}
impl<'a> ListAuthorsByIDs<'a> {
    pub const fn builder() -> ListAuthorsByIDsBuilder<'a, ((),)> {
        ListAuthorsByIDsBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAuthorsByIDsBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> ListAuthorsByIDsBuilder<'a, ((),)> {
    pub fn ids(self, ids: &'a [i64]) -> ListAuthorsByIDsBuilder<'a, (&'a [i64],)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsBuilder {
            fields: (ids,),
            _phantom,
        }
    }
}
impl<'a> ListAuthorsByIDsBuilder<'a, (&'a [i64],)> {
    pub const fn build(self) -> ListAuthorsByIDs<'a> {
        let (ids,) = self.fields;
        ListAuthorsByIDs { ids }
    }
}
