//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.28.0
//! sqlc-gen-rust version: v0.1.3

#[derive(Debug, Clone, Copy, sqlx::Type)]
#[sqlx(type_name = "order_status")]
pub enum OrderStatus {
    #[sqlx(rename = "pending")]
    Pending,
    #[sqlx(rename = "processing")]
    Processing,
    #[sqlx(rename = "shipped")]
    Shipped,
    #[sqlx(rename = "delivered")]
    Delivered,
    #[sqlx(rename = "cancelled")]
    Cancelled,
}
