//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.28.0
//! sqlc-gen-rust version: v0.1.11

pub struct CopyDataSink<C: std::ops::DerefMut<Target = sqlx::PgConnection>> {
    encode_buf: sqlx::postgres::PgArgumentBuffer,
    data_buf: Vec<u8>,
    copy_in: sqlx::postgres::PgCopyIn<C>,
}
impl<C: std::ops::DerefMut<Target = sqlx::PgConnection>> CopyDataSink<C> {
    const BUFFER_SIZE: usize = 4096;
    fn new(copy_in: sqlx::postgres::PgCopyIn<C>) -> Self {
        let mut data_buf = Vec::with_capacity(Self::BUFFER_SIZE);
        const COPY_SIGNATURE: &[u8] = &[
            b'P', b'G', b'C', b'O', b'P', b'Y', b'\n', 0xFF, b'\r', b'\n', 0x00,
        ];
        assert_eq!(COPY_SIGNATURE.len(), 11);
        data_buf.extend_from_slice(COPY_SIGNATURE);
        data_buf.extend(0_i32.to_be_bytes());
        data_buf.extend(0_i32.to_be_bytes());
        CopyDataSink {
            encode_buf: Default::default(),
            data_buf,
            copy_in,
        }
    }
    async fn send(&mut self) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let _copy_in = self.copy_in.send(self.data_buf.as_slice()).await?;
        self.data_buf.clear();
        Ok(())
    }
    /// Complete copy process and return number of rows affected.
    pub async fn finish(mut self) -> Result<u64, Box<dyn std::error::Error + Send + Sync>> {
        const COPY_TRAILER: &[u8] = &(-1_i16).to_be_bytes();
        self.data_buf.extend(COPY_TRAILER);
        self.send().await?;
        self.copy_in.finish().await.map_err(|e| e.into())
    }
    fn insert_row(&mut self) {
        let num_col = self.copy_in.num_columns() as i16;
        self.data_buf.extend(num_col.to_be_bytes());
    }
    async fn add<'q, T>(
        &mut self,
        value: &T,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>>
    where
        T: sqlx::Encode<'q, sqlx::Postgres> + sqlx::Type<sqlx::Postgres>,
    {
        let is_null = value.encode_by_ref(&mut self.encode_buf)?;
        match is_null {
            sqlx::encode::IsNull::Yes => {
                self.data_buf.extend((-1_i32).to_be_bytes());
            }
            sqlx::encode::IsNull::No => {
                self.data_buf
                    .extend((self.encode_buf.len() as i32).to_be_bytes());
                self.data_buf.extend_from_slice(self.encode_buf.as_slice());
            }
        }
        self.encode_buf.clear();
        if self.data_buf.len() > Self::BUFFER_SIZE {
            self.send().await?;
        }
        Ok(())
    }
}
#[derive(sqlx::FromRow)]
pub struct ListAuthorsByIDsRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
}
pub struct ListAuthorsByIDs<'a> {
    ids: &'a [i64],
}
impl<'a> ListAuthorsByIDs<'a> {
    pub const QUERY: &'static str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
ORDER BY id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> ListAuthorsByIDs<'a> {
    pub fn query_as(
        &'a self,
    ) -> sqlx::query::QueryAs<
        'a,
        sqlx::Postgres,
        ListAuthorsByIDsRow,
        <sqlx::Postgres as sqlx::Database>::Arguments<'a>,
    > {
        let q = sqlx::query_as(self.query_str());
        let q = q.bind(self.ids);
        q
    }
    pub fn query_many<'b, A>(
        &'a self,
        conn: A,
    ) -> impl Future<Output = Result<Vec<ListAuthorsByIDsRow>, sqlx::Error>> + Send + 'a
    where
        A: sqlx::Acquire<'b, Database = sqlx::Postgres> + Send + 'a,
    {
        async move {
            let mut conn = conn.acquire().await?;
            let vals = self.query_as().fetch_all(&mut *conn).await?;
            Ok(vals)
        }
    }
}
impl<'a> ListAuthorsByIDs<'a> {
    pub const fn builder() -> ListAuthorsByIDsBuilder<'a, ((),)> {
        ListAuthorsByIDsBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAuthorsByIDsBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> ListAuthorsByIDsBuilder<'a, ((),)> {
    pub fn ids(self, ids: &'a [i64]) -> ListAuthorsByIDsBuilder<'a, (&'a [i64],)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsBuilder {
            fields: (ids,),
            _phantom,
        }
    }
}
impl<'a> ListAuthorsByIDsBuilder<'a, (&'a [i64],)> {
    pub fn build(self) -> ListAuthorsByIDs<'a> {
        let (ids,) = self.fields;
        ListAuthorsByIDs { ids }
    }
}
#[derive(sqlx::FromRow)]
pub struct ListAuthorsByTwoIdListsRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
}
pub struct ListAuthorsByTwoIdLists<'a> {
    ids: &'a [i64],
    backup_ids: &'a [i64],
}
impl<'a> ListAuthorsByTwoIdLists<'a> {
    pub const QUERY: &'static str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
   OR id = ANY($2::bigint[])
ORDER BY id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> ListAuthorsByTwoIdLists<'a> {
    pub fn query_as(
        &'a self,
    ) -> sqlx::query::QueryAs<
        'a,
        sqlx::Postgres,
        ListAuthorsByTwoIdListsRow,
        <sqlx::Postgres as sqlx::Database>::Arguments<'a>,
    > {
        let q = sqlx::query_as(self.query_str());
        let q = q.bind(self.ids);
        let q = q.bind(self.backup_ids);
        q
    }
    pub fn query_many<'b, A>(
        &'a self,
        conn: A,
    ) -> impl Future<Output = Result<Vec<ListAuthorsByTwoIdListsRow>, sqlx::Error>> + Send + 'a
    where
        A: sqlx::Acquire<'b, Database = sqlx::Postgres> + Send + 'a,
    {
        async move {
            let mut conn = conn.acquire().await?;
            let vals = self.query_as().fetch_all(&mut *conn).await?;
            Ok(vals)
        }
    }
}
impl<'a> ListAuthorsByTwoIdLists<'a> {
    pub const fn builder() -> ListAuthorsByTwoIdListsBuilder<'a, ((), ())> {
        ListAuthorsByTwoIdListsBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAuthorsByTwoIdListsBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, BackupIds> ListAuthorsByTwoIdListsBuilder<'a, ((), BackupIds)> {
    pub fn ids(self, ids: &'a [i64]) -> ListAuthorsByTwoIdListsBuilder<'a, (&'a [i64], BackupIds)> {
        let ((), backup_ids) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByTwoIdListsBuilder {
            fields: (ids, backup_ids),
            _phantom,
        }
    }
}
impl<'a, Ids> ListAuthorsByTwoIdListsBuilder<'a, (Ids, ())> {
    pub fn backup_ids(
        self,
        backup_ids: &'a [i64],
    ) -> ListAuthorsByTwoIdListsBuilder<'a, (Ids, &'a [i64])> {
        let (ids, ()) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByTwoIdListsBuilder {
            fields: (ids, backup_ids),
            _phantom,
        }
    }
}
impl<'a> ListAuthorsByTwoIdListsBuilder<'a, (&'a [i64], &'a [i64])> {
    pub fn build(self) -> ListAuthorsByTwoIdLists<'a> {
        let (ids, backup_ids) = self.fields;
        ListAuthorsByTwoIdLists { ids, backup_ids }
    }
}
#[derive(sqlx::FromRow)]
pub struct ListAuthorsByIDsMixedRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
}
pub struct ListAuthorsByIDsMixed<'a> {
    ids: &'a [i64],
    min_id: i64,
    skip_ids: &'a [i64],
    excluded_name: &'a str,
}
impl<'a> ListAuthorsByIDsMixed<'a> {
    pub const QUERY: &'static str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
  AND id >= $2
  AND NOT (id = ANY($3::bigint[]))
  AND name <> $4
ORDER BY id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> ListAuthorsByIDsMixed<'a> {
    pub fn query_as(
        &'a self,
    ) -> sqlx::query::QueryAs<
        'a,
        sqlx::Postgres,
        ListAuthorsByIDsMixedRow,
        <sqlx::Postgres as sqlx::Database>::Arguments<'a>,
    > {
        let q = sqlx::query_as(self.query_str());
        let q = q.bind(self.ids);
        let q = q.bind(self.min_id);
        let q = q.bind(self.skip_ids);
        let q = q.bind(self.excluded_name);
        q
    }
    pub fn query_many<'b, A>(
        &'a self,
        conn: A,
    ) -> impl Future<Output = Result<Vec<ListAuthorsByIDsMixedRow>, sqlx::Error>> + Send + 'a
    where
        A: sqlx::Acquire<'b, Database = sqlx::Postgres> + Send + 'a,
    {
        async move {
            let mut conn = conn.acquire().await?;
            let vals = self.query_as().fetch_all(&mut *conn).await?;
            Ok(vals)
        }
    }
}
impl<'a> ListAuthorsByIDsMixed<'a> {
    pub const fn builder() -> ListAuthorsByIDsMixedBuilder<'a, ((), (), (), ())> {
        ListAuthorsByIDsMixedBuilder {
            fields: ((), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAuthorsByIDsMixedBuilder<'a, Fields = ((), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, MinId, SkipIds, ExcludedName>
    ListAuthorsByIDsMixedBuilder<'a, ((), MinId, SkipIds, ExcludedName)>
{
    pub fn ids(
        self,
        ids: &'a [i64],
    ) -> ListAuthorsByIDsMixedBuilder<'a, (&'a [i64], MinId, SkipIds, ExcludedName)> {
        let ((), min_id, skip_ids, excluded_name) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, min_id, skip_ids, excluded_name),
            _phantom,
        }
    }
}
impl<'a, Ids, SkipIds, ExcludedName>
    ListAuthorsByIDsMixedBuilder<'a, (Ids, (), SkipIds, ExcludedName)>
{
    pub fn min_id(
        self,
        min_id: i64,
    ) -> ListAuthorsByIDsMixedBuilder<'a, (Ids, i64, SkipIds, ExcludedName)> {
        let (ids, (), skip_ids, excluded_name) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, min_id, skip_ids, excluded_name),
            _phantom,
        }
    }
}
impl<'a, Ids, MinId, ExcludedName>
    ListAuthorsByIDsMixedBuilder<'a, (Ids, MinId, (), ExcludedName)>
{
    pub fn skip_ids(
        self,
        skip_ids: &'a [i64],
    ) -> ListAuthorsByIDsMixedBuilder<'a, (Ids, MinId, &'a [i64], ExcludedName)> {
        let (ids, min_id, (), excluded_name) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, min_id, skip_ids, excluded_name),
            _phantom,
        }
    }
}
impl<'a, Ids, MinId, SkipIds> ListAuthorsByIDsMixedBuilder<'a, (Ids, MinId, SkipIds, ())> {
    pub fn excluded_name(
        self,
        excluded_name: &'a str,
    ) -> ListAuthorsByIDsMixedBuilder<'a, (Ids, MinId, SkipIds, &'a str)> {
        let (ids, min_id, skip_ids, ()) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, min_id, skip_ids, excluded_name),
            _phantom,
        }
    }
}
impl<'a> ListAuthorsByIDsMixedBuilder<'a, (&'a [i64], i64, &'a [i64], &'a str)> {
    pub fn build(self) -> ListAuthorsByIDsMixed<'a> {
        let (ids, min_id, skip_ids, excluded_name) = self.fields;
        ListAuthorsByIDsMixed {
            ids,
            min_id,
            skip_ids,
            excluded_name,
        }
    }
}
