//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.30.0
//! sqlc-gen-rust version: v0.1.11

#[derive(sqlx::FromRow)]
pub struct CreateAuthorRow {}
pub struct CreateAuthor<'a> {
    name: &'a str,
    bio: Option<&'a str>,
}
impl<'a> CreateAuthor<'a> {
    pub const QUERY: &'static str = r"INSERT INTO authors (
  name, bio
) VALUES (
  ?, ?
)";
    pub fn query_as(
        &'a self,
    ) -> sqlx::query::QueryAs<
        'a,
        sqlx::MySql,
        CreateAuthorRow,
        <sqlx::MySql as sqlx::Database>::Arguments<'a>,
    > {
        sqlx::query_as::<_, CreateAuthorRow>(Self::QUERY)
            .bind(self.name)
            .bind(self.bio)
    }
    pub fn execute<'b, A>(
        &'a self,
        conn: A,
    ) -> impl Future<Output = Result<<sqlx::MySql as sqlx::Database>::QueryResult, sqlx::Error>>
    + Send
    + 'a
    where
        A: sqlx::Acquire<'b, Database = sqlx::MySql> + Send + 'a,
    {
        async move {
            let mut conn = conn.acquire().await?;
            sqlx::query(Self::QUERY)
                .bind(self.name)
                .bind(self.bio)
                .execute(&mut *conn)
                .await
        }
    }
}
impl<'a> CreateAuthor<'a> {
    pub const fn builder() -> CreateAuthorBuilder<'a, ((), ())> {
        CreateAuthorBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct CreateAuthorBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Bio> CreateAuthorBuilder<'a, ((), Bio)> {
    pub fn name(self, name: &'a str) -> CreateAuthorBuilder<'a, (&'a str, Bio)> {
        let ((), bio) = self.fields;
        let _phantom = self._phantom;
        CreateAuthorBuilder {
            fields: (name, bio),
            _phantom,
        }
    }
}
impl<'a, Name> CreateAuthorBuilder<'a, (Name, ())> {
    pub fn bio(self, bio: Option<&'a str>) -> CreateAuthorBuilder<'a, (Name, Option<&'a str>)> {
        let (name, ()) = self.fields;
        let _phantom = self._phantom;
        CreateAuthorBuilder {
            fields: (name, bio),
            _phantom,
        }
    }
}
impl<'a> CreateAuthorBuilder<'a, (&'a str, Option<&'a str>)> {
    pub const fn build(self) -> CreateAuthor<'a> {
        let (name, bio) = self.fields;
        CreateAuthor { name, bio }
    }
}
#[derive(sqlx::FromRow)]
pub struct GetAuthorsByIdsRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
    #[sqlx(rename = "bio")]
    pub bio: Option<String>,
}
pub struct GetAuthorsByIds<'a> {
    ids: &'a [i64],
}
impl<'a> GetAuthorsByIds<'a> {
    pub const QUERY: &'static str = r"SELECT id, name, bio FROM authors
WHERE id IN (/*SLICE:ids*/?)";
    fn expand_query(&self) -> String {
        let mut query = Self::QUERY.to_string();
        if self.ids.is_empty() {
            query = query.replacen("/*SLICE:ids*/?", "NULL", 1);
        } else {
            query = query.replacen("/*SLICE:ids*/?", &",?".repeat(self.ids.len())[1..], 1);
        }
        query
    }
    pub fn query_many<'b, A>(
        &'a self,
        conn: A,
    ) -> impl Future<Output = Result<Vec<GetAuthorsByIdsRow>, sqlx::Error>> + Send + 'a
    where
        A: sqlx::Acquire<'b, Database = sqlx::MySql> + Send + 'a,
    {
        async move {
            let mut conn = conn.acquire().await?;
            let query_str = self.expand_query();
            let mut q = sqlx::query_as::<_, GetAuthorsByIdsRow>(&query_str);
            for v in self.ids {
                q = q.bind(v);
            }
            let vals = q.fetch_all(&mut *conn).await?;
            Ok(vals)
        }
    }
}
impl<'a> GetAuthorsByIds<'a> {
    pub const fn builder() -> GetAuthorsByIdsBuilder<'a, ((),)> {
        GetAuthorsByIdsBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAuthorsByIdsBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetAuthorsByIdsBuilder<'a, ((),)> {
    pub fn ids(self, ids: &'a [i64]) -> GetAuthorsByIdsBuilder<'a, (&'a [i64],)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        GetAuthorsByIdsBuilder {
            fields: (ids,),
            _phantom,
        }
    }
}
impl<'a> GetAuthorsByIdsBuilder<'a, (&'a [i64],)> {
    pub const fn build(self) -> GetAuthorsByIds<'a> {
        let (ids,) = self.fields;
        GetAuthorsByIds { ids }
    }
}
#[derive(sqlx::FromRow)]
pub struct GetAuthorsByIdsAndNameRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
    #[sqlx(rename = "bio")]
    pub bio: Option<String>,
}
pub struct GetAuthorsByIdsAndName<'a> {
    name: &'a str,
    ids: &'a [i64],
}
impl<'a> GetAuthorsByIdsAndName<'a> {
    pub const QUERY: &'static str = r"SELECT id, name, bio FROM authors
WHERE name = ? AND id IN (/*SLICE:ids*/?)";
    fn expand_query(&self) -> String {
        let mut query = Self::QUERY.to_string();
        if self.ids.is_empty() {
            query = query.replacen("/*SLICE:ids*/?", "NULL", 1);
        } else {
            query = query.replacen("/*SLICE:ids*/?", &",?".repeat(self.ids.len())[1..], 1);
        }
        query
    }
    pub fn query_many<'b, A>(
        &'a self,
        conn: A,
    ) -> impl Future<Output = Result<Vec<GetAuthorsByIdsAndNameRow>, sqlx::Error>> + Send + 'a
    where
        A: sqlx::Acquire<'b, Database = sqlx::MySql> + Send + 'a,
    {
        async move {
            let mut conn = conn.acquire().await?;
            let query_str = self.expand_query();
            let mut q = sqlx::query_as::<_, GetAuthorsByIdsAndNameRow>(&query_str);
            q = q.bind(self.name);
            for v in self.ids {
                q = q.bind(v);
            }
            let vals = q.fetch_all(&mut *conn).await?;
            Ok(vals)
        }
    }
}
impl<'a> GetAuthorsByIdsAndName<'a> {
    pub const fn builder() -> GetAuthorsByIdsAndNameBuilder<'a, ((), ())> {
        GetAuthorsByIdsAndNameBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAuthorsByIdsAndNameBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Ids> GetAuthorsByIdsAndNameBuilder<'a, ((), Ids)> {
    pub fn name(self, name: &'a str) -> GetAuthorsByIdsAndNameBuilder<'a, (&'a str, Ids)> {
        let ((), ids) = self.fields;
        let _phantom = self._phantom;
        GetAuthorsByIdsAndNameBuilder {
            fields: (name, ids),
            _phantom,
        }
    }
}
impl<'a, Name> GetAuthorsByIdsAndNameBuilder<'a, (Name, ())> {
    pub fn ids(self, ids: &'a [i64]) -> GetAuthorsByIdsAndNameBuilder<'a, (Name, &'a [i64])> {
        let (name, ()) = self.fields;
        let _phantom = self._phantom;
        GetAuthorsByIdsAndNameBuilder {
            fields: (name, ids),
            _phantom,
        }
    }
}
impl<'a> GetAuthorsByIdsAndNameBuilder<'a, (&'a str, &'a [i64])> {
    pub const fn build(self) -> GetAuthorsByIdsAndName<'a> {
        let (name, ids) = self.fields;
        GetAuthorsByIdsAndName { name, ids }
    }
}
