//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.28.0
//! sqlc-gen-rust version: v0.1.12

pub trait RusqliteClient {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>>;
}
impl RusqliteClient for rusqlite::Connection {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        self.prepare(sql)
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        rusqlite::Connection::prepare(&self, sql)
    }
}
pub struct ListAuthorsByIDsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
        })
    }
}
pub struct ListAuthorsByIDs<'a> {
    ids: &'a [i64],
    __query: String,
}
impl<'a> ListAuthorsByIDs<'a> {
    pub const QUERY: &'static str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?)
ORDER BY id";
    pub fn query_str(&self) -> &str {
        &self.__query
    }
}
impl<'a> ListAuthorsByIDs<'a> {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<ListAuthorsByIDsRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), ListAuthorsByIDsRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        rusqlite::params_from_iter(
            core::iter::empty().chain(self.ids.iter().map(|v| v as &dyn rusqlite::ToSql)),
        )
    }
}
impl<'a> ListAuthorsByIDs<'a> {
    pub const fn builder() -> ListAuthorsByIDsBuilder<'a, ((),)> {
        ListAuthorsByIDsBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAuthorsByIDsBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> ListAuthorsByIDsBuilder<'a, ((),)> {
    pub fn ids(self, ids: &'a [i64]) -> ListAuthorsByIDsBuilder<'a, (&'a [i64],)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsBuilder {
            fields: (ids,),
            _phantom,
        }
    }
}
impl<'a> ListAuthorsByIDsBuilder<'a, (&'a [i64],)> {
    pub fn build(self) -> ListAuthorsByIDs<'a> {
        let (ids,) = self.fields;
        let __query = ListAuthorsByIDs::QUERY;
        let __query = match ids.len() {
            0 => __query.replace("/*SLICE:ids*/?", "NULL"),
            1 => __query.replace("/*SLICE:ids*/?", "?"),
            n => {
                let to = core::iter::once("?")
                    .chain(core::iter::repeat(",?").take(n - 1))
                    .collect::<String>();
                __query.replace("/*SLICE:ids*/?", &to)
            }
        };
        ListAuthorsByIDs {
            ids,
            __query: __query.into(),
        }
    }
}
pub struct ListAuthorsByTwoIdListsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByTwoIdListsRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
        })
    }
}
pub struct ListAuthorsByTwoIdLists<'a> {
    ids: &'a [i64],
    backup_ids: &'a [i64],
    __query: String,
}
impl<'a> ListAuthorsByTwoIdLists<'a> {
    pub const QUERY: &'static str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?)
   OR id IN (/*SLICE:backup_ids*/?)
ORDER BY id";
    pub fn query_str(&self) -> &str {
        &self.__query
    }
}
impl<'a> ListAuthorsByTwoIdLists<'a> {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<ListAuthorsByTwoIdListsRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), ListAuthorsByTwoIdListsRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        rusqlite::params_from_iter(
            core::iter::empty()
                .chain(self.ids.iter().map(|v| v as &dyn rusqlite::ToSql))
                .chain(self.backup_ids.iter().map(|v| v as &dyn rusqlite::ToSql)),
        )
    }
}
impl<'a> ListAuthorsByTwoIdLists<'a> {
    pub const fn builder() -> ListAuthorsByTwoIdListsBuilder<'a, ((), ())> {
        ListAuthorsByTwoIdListsBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAuthorsByTwoIdListsBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, BackupIds> ListAuthorsByTwoIdListsBuilder<'a, ((), BackupIds)> {
    pub fn ids(self, ids: &'a [i64]) -> ListAuthorsByTwoIdListsBuilder<'a, (&'a [i64], BackupIds)> {
        let ((), backup_ids) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByTwoIdListsBuilder {
            fields: (ids, backup_ids),
            _phantom,
        }
    }
}
impl<'a, Ids> ListAuthorsByTwoIdListsBuilder<'a, (Ids, ())> {
    pub fn backup_ids(
        self,
        backup_ids: &'a [i64],
    ) -> ListAuthorsByTwoIdListsBuilder<'a, (Ids, &'a [i64])> {
        let (ids, ()) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByTwoIdListsBuilder {
            fields: (ids, backup_ids),
            _phantom,
        }
    }
}
impl<'a> ListAuthorsByTwoIdListsBuilder<'a, (&'a [i64], &'a [i64])> {
    pub fn build(self) -> ListAuthorsByTwoIdLists<'a> {
        let (ids, backup_ids) = self.fields;
        let __query = ListAuthorsByTwoIdLists::QUERY;
        let __query = match ids.len() {
            0 => __query.replace("/*SLICE:ids*/?", "NULL"),
            1 => __query.replace("/*SLICE:ids*/?", "?"),
            n => {
                let to = core::iter::once("?")
                    .chain(core::iter::repeat(",?").take(n - 1))
                    .collect::<String>();
                __query.replace("/*SLICE:ids*/?", &to)
            }
        };
        let __query = match backup_ids.len() {
            0 => __query.replace("/*SLICE:backup_ids*/?", "NULL"),
            1 => __query.replace("/*SLICE:backup_ids*/?", "?"),
            n => {
                let to = core::iter::once("?")
                    .chain(core::iter::repeat(",?").take(n - 1))
                    .collect::<String>();
                __query.replace("/*SLICE:backup_ids*/?", &to)
            }
        };
        ListAuthorsByTwoIdLists {
            ids,
            backup_ids,
            __query: __query.into(),
        }
    }
}
pub struct ListAuthorsByIDsMixedRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsMixedRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
        })
    }
}
pub struct ListAuthorsByIDsMixed<'a> {
    ids: &'a [i64],
    id: i64,
    skip_ids: &'a [i64],
    name: &'a str,
    __query: String,
}
impl<'a> ListAuthorsByIDsMixed<'a> {
    pub const QUERY: &'static str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?)
  AND id >= ?
  AND id NOT IN (/*SLICE:skip_ids*/?)
  AND name <> ?
ORDER BY id";
    pub fn query_str(&self) -> &str {
        &self.__query
    }
}
impl<'a> ListAuthorsByIDsMixed<'a> {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<ListAuthorsByIDsMixedRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), ListAuthorsByIDsMixedRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        rusqlite::params_from_iter(
            core::iter::empty()
                .chain(self.ids.iter().map(|v| v as &dyn rusqlite::ToSql))
                .chain(core::iter::once(&self.id as &dyn rusqlite::ToSql))
                .chain(self.skip_ids.iter().map(|v| v as &dyn rusqlite::ToSql))
                .chain(core::iter::once(&self.name as &dyn rusqlite::ToSql)),
        )
    }
}
impl<'a> ListAuthorsByIDsMixed<'a> {
    pub const fn builder() -> ListAuthorsByIDsMixedBuilder<'a, ((), (), (), ())> {
        ListAuthorsByIDsMixedBuilder {
            fields: ((), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAuthorsByIDsMixedBuilder<'a, Fields = ((), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Id, SkipIds, Name> ListAuthorsByIDsMixedBuilder<'a, ((), Id, SkipIds, Name)> {
    pub fn ids(
        self,
        ids: &'a [i64],
    ) -> ListAuthorsByIDsMixedBuilder<'a, (&'a [i64], Id, SkipIds, Name)> {
        let ((), id, skip_ids, name) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, id, skip_ids, name),
            _phantom,
        }
    }
}
impl<'a, Ids, SkipIds, Name> ListAuthorsByIDsMixedBuilder<'a, (Ids, (), SkipIds, Name)> {
    pub fn id(self, id: i64) -> ListAuthorsByIDsMixedBuilder<'a, (Ids, i64, SkipIds, Name)> {
        let (ids, (), skip_ids, name) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, id, skip_ids, name),
            _phantom,
        }
    }
}
impl<'a, Ids, Id, Name> ListAuthorsByIDsMixedBuilder<'a, (Ids, Id, (), Name)> {
    pub fn skip_ids(
        self,
        skip_ids: &'a [i64],
    ) -> ListAuthorsByIDsMixedBuilder<'a, (Ids, Id, &'a [i64], Name)> {
        let (ids, id, (), name) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, id, skip_ids, name),
            _phantom,
        }
    }
}
impl<'a, Ids, Id, SkipIds> ListAuthorsByIDsMixedBuilder<'a, (Ids, Id, SkipIds, ())> {
    pub fn name(
        self,
        name: &'a str,
    ) -> ListAuthorsByIDsMixedBuilder<'a, (Ids, Id, SkipIds, &'a str)> {
        let (ids, id, skip_ids, ()) = self.fields;
        let _phantom = self._phantom;
        ListAuthorsByIDsMixedBuilder {
            fields: (ids, id, skip_ids, name),
            _phantom,
        }
    }
}
impl<'a> ListAuthorsByIDsMixedBuilder<'a, (&'a [i64], i64, &'a [i64], &'a str)> {
    pub fn build(self) -> ListAuthorsByIDsMixed<'a> {
        let (ids, id, skip_ids, name) = self.fields;
        let __query = ListAuthorsByIDsMixed::QUERY;
        let __query = match ids.len() {
            0 => __query.replace("/*SLICE:ids*/?", "NULL"),
            1 => __query.replace("/*SLICE:ids*/?", "?"),
            n => {
                let to = core::iter::once("?")
                    .chain(core::iter::repeat(",?").take(n - 1))
                    .collect::<String>();
                __query.replace("/*SLICE:ids*/?", &to)
            }
        };
        let __query = match skip_ids.len() {
            0 => __query.replace("/*SLICE:skip_ids*/?", "NULL"),
            1 => __query.replace("/*SLICE:skip_ids*/?", "?"),
            n => {
                let to = core::iter::once("?")
                    .chain(core::iter::repeat(",?").take(n - 1))
                    .collect::<String>();
                __query.replace("/*SLICE:skip_ids*/?", &to)
            }
        };
        ListAuthorsByIDsMixed {
            ids,
            id,
            skip_ids,
            name,
            __query: __query.into(),
        }
    }
}
