//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.28.0
//! sqlc-gen-rust version: v0.1.11

use deadpool_postgres::tokio_postgres::types::ToSql;
pub struct CountPilotsRow {
    pub count: i64,
}
impl CountPilotsRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self { count: row.try_get(0)? })
    }
}
pub struct CountPilots;
impl CountPilots {
    pub const QUERY: &'static str = r"SELECT COUNT(*) FROM pilots";
    pub async fn query_one(
        &self,
        client: &impl deadpool_postgres::GenericClient,
    ) -> Result<CountPilotsRow, deadpool_postgres::tokio_postgres::Error> {
        let row = client.query_one(Self::QUERY, &self.as_params()).await?;
        CountPilotsRow::from_row(&row)
    }
    pub async fn query_opt(
        &self,
        client: &impl deadpool_postgres::GenericClient,
    ) -> Result<Option<CountPilotsRow>, deadpool_postgres::tokio_postgres::Error> {
        let row = client.query_opt(Self::QUERY, &self.as_params()).await?;
        match row {
            Some(row) => Ok(Some(CountPilotsRow::from_row(&row)?)),
            None => Ok(None),
        }
    }
    pub fn as_params(&self) -> [&(dyn ToSql + Sync); 0] {
        []
    }
}
impl CountPilots {
    pub const fn builder() -> CountPilotsBuilder<'static, ()> {
        CountPilotsBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct CountPilotsBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> CountPilotsBuilder<'a, ()> {
    pub const fn build(self) -> CountPilots {
        let () = self.fields;
        CountPilots {}
    }
}
pub struct ListPilotsRow {
    pub id: i32,
    pub name: String,
}
impl ListPilotsRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
        })
    }
}
pub struct ListPilots;
impl ListPilots {
    pub const QUERY: &'static str = r"SELECT id, name FROM pilots LIMIT 5";
    pub async fn query_stream(
        &self,
        client: &impl deadpool_postgres::GenericClient,
    ) -> Result<
        deadpool_postgres::tokio_postgres::RowStream,
        deadpool_postgres::tokio_postgres::Error,
    > {
        let st = client.query_raw(Self::QUERY, self.as_params().into_iter()).await?;
        Ok(st)
    }
    pub async fn query_many(
        &self,
        client: &impl deadpool_postgres::GenericClient,
    ) -> Result<Vec<ListPilotsRow>, deadpool_postgres::tokio_postgres::Error> {
        let rows = client.query(Self::QUERY, &self.as_params()).await?;
        rows.into_iter().map(|r| ListPilotsRow::from_row(&r)).collect()
    }
    pub fn as_params(&self) -> [&(dyn ToSql + Sync); 0] {
        []
    }
}
impl ListPilots {
    pub const fn builder() -> ListPilotsBuilder<'static, ()> {
        ListPilotsBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListPilotsBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> ListPilotsBuilder<'a, ()> {
    pub const fn build(self) -> ListPilots {
        let () = self.fields;
        ListPilots {}
    }
}
pub struct DeletePilotRow {}
impl DeletePilotRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct DeletePilot {
    id: i32,
}
impl DeletePilot {
    pub const QUERY: &'static str = r"DELETE FROM pilots WHERE id = $1";
    pub async fn execute(
        &self,
        client: &impl deadpool_postgres::GenericClient,
    ) -> Result<u64, deadpool_postgres::tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_params()).await
    }
    pub fn as_params(&self) -> [&(dyn ToSql + Sync); 1] {
        [&self.id]
    }
}
impl DeletePilot {
    pub const fn builder() -> DeletePilotBuilder<'static, ((),)> {
        DeletePilotBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct DeletePilotBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> DeletePilotBuilder<'a, ((),)> {
    pub fn id(self, id: i32) -> DeletePilotBuilder<'a, (i32,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        DeletePilotBuilder {
            fields: (id,),
            _phantom,
        }
    }
}
impl<'a> DeletePilotBuilder<'a, (i32,)> {
    pub const fn build(self) -> DeletePilot {
        let (id,) = self.fields;
        DeletePilot { id }
    }
}
