[package]
name = "e-commerce"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { workspace = true }
postgres-types = { workspace = true }
tokio-postgres = { workspace = true }
serde_json = { workspace = true }
