name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions: {}

jobs:
  release:
    if: ${{ github.actor == github.repository_owner }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Rust
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
        with:
          targets: wasm32-wasip1
          cache-base: main
      - name: Setup Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
      - name: Setup Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: "29.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}         
      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@c0209b9199cd1cce6a14fc27cabcec491b651761 # v4.0.0
        with:
          sqlc-version: '1.28.0'
      - name: Build plugin
        run: |
          just build-release
      - name: Create Release
        run: |
          gh release create "${VERSION}" --generate-notes 
          gh release upload "${VERSION}" target/wasm32-wasip1/release/sqlc-gen-rust.wasm
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}